apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    purpose: monitoring-stack
  annotations:
    description: "Namespace for monitoring tools like Prometheus, Grafana, AlertManager"