apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
  namespace: default
  labels:
    app: webapp
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  # LoadBalancer specific annotations (cloud provider dependent)
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-type: nlb
  #   service.beta.kubernetes.io/azure-load-balancer-resource-group: myResourceGroup