apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: default
  labels:
    app: webapp
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080
    protocol: TCP
    name: http