apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-read-binding
subjects:
- kind: ServiceAccount
  name: example-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-reader
  apiGroup: rbac.authorization.k8s.io
---


# NOTES:
# - ClusterRoleBinding attaches ClusterRole to subjects across the cluster.
# - If you bind ClusterRole with RoleBinding → scope is limited to the namespace.
