apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: example-sa
  namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---


# NOTES:
# - RoleBinding attaches a Role to subjects (users, groups, or ServiceAccounts).
# - Subjects:
#   * kind: User, Group, or ServiceAccount
# - RoleBinding is namespace-scoped.
