apiVersion: v1
kind: Pod
metadata:
  name: pod-with-sc
spec:
  containers:
  - name: secure-container
    image: nginx
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 1000
      capabilities:
        drop: [ "ALL" ] # drop all Linux capabilities
        add: [ "NET_BIND_SERVICE" ] # allow binding to ports <1024
      readOnlyRootFilesystem: true
---


# NOTES:
# - SecurityContext is container-specific (overrides PodSecurityContext).
# - Used for least privilege principle:
#   * disable root access
#   * drop Linux capabilities
#   * enforce read-only FS
# - applied at container level, not Pod level.
