apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-sa
  namespace: default
---


# NOTES:
# - ServiceAccounts provide identity for Pods when interacting with the API server.
# - By default, Pods use the "default" ServiceAccount in their namespace.
# - You can assign a custom ServiceAccount in Pod spec with `serviceAccountName`.
