apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs # Plugin that provisions volumes
parameters:
  type: gp2 # AWS EBS volume type
reclaimPolicy: Delete # Retain | Delete
volumeBindingMode: Immediate # Immediate | WaitForFirstConsumer

# Notes
# provisioner varies by cloud:
# AWS: kubernetes.io/aws-ebs
# GCP: kubernetes.io/gce-pd
# Azure: kubernetes.io/azure-disk
# CSI drivers: csi.drivername

# volumeBindingMode:
# Immediate → bind as soon as PVC is created.
# WaitForFirstConsumer → wait until a Pod is scheduled (avoids mismatch in zones).
