apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: example-daemonset
spec:
  selector:
    matchLabels:
      app: my-daemon
  template:
    metadata:
      labels:
        app: my-daemon
    spec:
      containers:
      - name: daemon-container
        image: busybox
        command: [ "sh", "-c", "while true; do echo Hello from DaemonSet; sleep 10; done" ]
