apiVersion: v1
kind: Service
metadata:
  name: my-service-lb
spec:
  type: LoadBalancer # Requests external load balancer from cloud
  selector:
    app: my-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
