apiVersion: v1
kind: Secret
metadata:
  name: webapp-secrets
  namespace: default
  labels:
    app: webapp
type: Opaque
data:
  # Base64 encoded values
  # To encode: echo -n 'your-password' | base64
  database-password: cGFzc3dvcmQxMjM=  # password123
  api-key: YWJjZGVmZ2hpams=  # abcdefghijk
  jwt-secret: c3VwZXItc2VjcmV0LWp3dC1rZXk=  # super-secret-jwt-key
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  # Docker registry credentials
  # Create with: kubectl create secret docker-registry <name> --docker-server=<server> --docker-username=<username> --docker-password=<password> --docker-email=<email> --dry-run=client -o yaml
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ1c2VyIiwicGFzc3dvcmQiOiJwYXNzIiwiYXV0aCI6ImRYTmxjanB3WVhOeiJ9fX0=